<a href="https://colab.research.google.com/github/Chandni0369/ML-LAB-D11ADA-57/blob/main/exp%2010/ML_exp10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

n = int(input("Enter number of inputs: "))
X = np.array([list(map(int, np.binary_repr(i, n))) for i in range(2**n)])
print("\nAll possible input combinations:")
print(X)

Enter number of inputs: 3

All possible input combinations:
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [5]:
y = np.array([1 if np.all(x == 1) else -1 for x in X])
print("\nTarget Output (for AND Gate):")
print(y)

weights = np.zeros(n)
bias = 0
lr = 1  #learning rate


Target Output (for AND Gate):
[-1 -1 -1 -1 -1 -1 -1  1]


In [7]:
records = []

for i in range(len(X)):
    x = np.where(X[i] == 0, -1, 1)   # convert 0→-1 for bipolar input
    weights += lr * x * y[i]
    bias += lr * y[i]
    records.append([i+1, *weights, bias])

cols = ['Sample', *[f'W{i+1}' for i in range(n)], 'Bias']
df_weights = pd.DataFrame(records, columns=cols)

print("\nHebbian Learning Weight Update Table:\n")
print(df_weights.to_string(index=False))


Hebbian Learning Weight Update Table:

 Sample  W1  W2  W3  Bias
      1 3.0 3.0 3.0    -7
      2 4.0 4.0 2.0    -8
      3 5.0 3.0 3.0    -9
      4 6.0 2.0 2.0   -10
      5 5.0 3.0 3.0   -11
      6 4.0 4.0 2.0   -12
      7 3.0 3.0 3.0   -13
      8 4.0 4.0 4.0   -12


In [9]:
print("\nFinal learned weights and bias:")
print("Weights:", weights)
print("Bias:", bias)


Final learned weights and bias:
Weights: [4. 4. 4.]
Bias: -12


In [10]:
print("\nTesting the learned Hebbian model:\n")

for i in range(len(X)):
    x = np.where(X[i] == 0, -1, 1)
    net = np.dot(x, weights) + bias
    output = 1 if net > 0 else -1
    print(f"Input: {x}  |  Net: {net:.2f}  |  Output: {output}")


Testing the learned Hebbian model:

Input: [-1 -1 -1]  |  Net: -24.00  |  Output: -1
Input: [-1 -1  1]  |  Net: -16.00  |  Output: -1
Input: [-1  1 -1]  |  Net: -16.00  |  Output: -1
Input: [-1  1  1]  |  Net: -8.00  |  Output: -1
Input: [ 1 -1 -1]  |  Net: -16.00  |  Output: -1
Input: [ 1 -1  1]  |  Net: -8.00  |  Output: -1
Input: [ 1  1 -1]  |  Net: -8.00  |  Output: -1
Input: [1 1 1]  |  Net: 0.00  |  Output: -1
