<a href="https://colab.research.google.com/github/Chandni0369/ML-LAB-D11ADA-57/blob/main/exp%208/ML_exp8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np
import pandas as pd

def MP_Neuron(inputs, weights, threshold):
    total = np.dot(inputs, weights)
    return 1 if total >= threshold else 0

In [7]:
n = int(input("Enter number of inputs: "))
X = np.array([list(map(int, np.binary_repr(i, n))) for i in range(2**n)])
print("\nAll possible input combinations:")
print(X)

Enter number of inputs: 3

All possible input combinations:
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [9]:
weights = np.ones(n)
threshold_and = n
y_and = [MP_Neuron(x, weights, threshold_and) for x in X]

df_and = pd.DataFrame(
    np.column_stack((X, y_and)),
    columns=[f'X{i+1}' for i in range(n)] + ['AND Output']
)

print("\nAND Gate Truth Table:\n")
print(df_and.to_string(index=False))


AND Gate Truth Table:

 X1  X2  X3  AND Output
  0   0   0           0
  0   0   1           0
  0   1   0           0
  0   1   1           0
  1   0   0           0
  1   0   1           0
  1   1   0           0
  1   1   1           1


In [10]:
weights = np.ones(n)
threshold_or = 1
y_or = [MP_Neuron(x, weights, threshold_or) for x in X]

df_or = pd.DataFrame(
    np.column_stack((X, y_or)),
    columns=[f'X{i+1}' for i in range(n)] + ['OR Output']
)

print("\nOR Gate Truth Table:\n")
print(df_or.to_string(index=False))



OR Gate Truth Table:

 X1  X2  X3  OR Output
  0   0   0          0
  0   0   1          1
  0   1   0          1
  0   1   1          1
  1   0   0          1
  1   0   1          1
  1   1   0          1
  1   1   1          1
